server:
  #logger_plugin: file_logger


decision_logs:
  plugin: file_logger
  #console: true


plugins:
  grpc:
    addr: ":50051"
  danube:
    issuer: "did:web:did.dumss.me"
    keyPath: "key.pem"
    sigAlgo: "PS256"
    verificationMethod: "did:web:did.dumss.me#v1-2026"
    path: "/danube"
    policy: "data.compliance.legalPerson"
    idPrefix: "https://example.com/trustedParty"
  file_logger:
    path: ./decision.log
    max_size_mb: 100
    max_age_days: 28
    max_backups: 3
    #compress: true
    level: debug
  external_pdp:
    sources:
      legalPerson: "http://127.0.0.1:8181/v1/data/verify/legalPerson"
      danube: "http://127.0.0.1:8181/danube"