// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: opa.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// path is the data path to evaluate, e.g. "verify/legalPersonData".
	Path          string           `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Input         *structpb.Struct `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_opa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_opa_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *QueryRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

type QueryResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result *structpb.Struct       `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// short if policies define allowed:=false-> allowed:=true
	Allowed       bool `protobuf:"varint,3,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_opa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_opa_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_opa_proto protoreflect.FileDescriptor

const file_opa_proto_rawDesc = "" +
	"\n" +
	"\topa.proto\x12\vgaiaxopa.v1\x1a\x1cgoogle/protobuf/struct.proto\"Q\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05input\"p\n" +
	"\rQueryResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aallowed\x18\x03 \x01(\bR\aallowed2L\n" +
	"\n" +
	"OPAService\x12>\n" +
	"\x05Query\x12\x19.gaiaxopa.v1.QueryRequest\x1a\x1a.gaiaxopa.v1.QueryResponseB\x11Z\x0finternal/grpcpbb\x06proto3"

var (
	file_opa_proto_rawDescOnce sync.Once
	file_opa_proto_rawDescData []byte
)

func file_opa_proto_rawDescGZIP() []byte {
	file_opa_proto_rawDescOnce.Do(func() {
		file_opa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opa_proto_rawDesc), len(file_opa_proto_rawDesc)))
	})
	return file_opa_proto_rawDescData
}

var file_opa_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_opa_proto_goTypes = []any{
	(*QueryRequest)(nil),    // 0: gaiaxopa.v1.QueryRequest
	(*QueryResponse)(nil),   // 1: gaiaxopa.v1.QueryResponse
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_opa_proto_depIdxs = []int32{
	2, // 0: gaiaxopa.v1.QueryRequest.input:type_name -> google.protobuf.Struct
	2, // 1: gaiaxopa.v1.QueryResponse.result:type_name -> google.protobuf.Struct
	0, // 2: gaiaxopa.v1.OPAService.Query:input_type -> gaiaxopa.v1.QueryRequest
	1, // 3: gaiaxopa.v1.OPAService.Query:output_type -> gaiaxopa.v1.QueryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_opa_proto_init() }
func file_opa_proto_init() {
	if File_opa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opa_proto_rawDesc), len(file_opa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_opa_proto_goTypes,
		DependencyIndexes: file_opa_proto_depIdxs,
		MessageInfos:      file_opa_proto_msgTypes,
	}.Build()
	File_opa_proto = out.File
	file_opa_proto_goTypes = nil
	file_opa_proto_depIdxs = nil
}
