// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: opa.proto

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OPAService_Query_FullMethodName = "/gaiaxopa.v1.OPAService/Query"
)

// OPAServiceClient is the client API for OPAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OPAServiceClient interface {
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type oPAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOPAServiceClient(cc grpc.ClientConnInterface) OPAServiceClient {
	return &oPAServiceClient{cc}
}

func (c *oPAServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, OPAService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OPAServiceServer is the server API for OPAService service.
// All implementations must embed UnimplementedOPAServiceServer
// for forward compatibility.
type OPAServiceServer interface {
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedOPAServiceServer()
}

// UnimplementedOPAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOPAServiceServer struct{}

func (UnimplementedOPAServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedOPAServiceServer) mustEmbedUnimplementedOPAServiceServer() {}
func (UnimplementedOPAServiceServer) testEmbeddedByValue()                    {}

// UnsafeOPAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OPAServiceServer will
// result in compilation errors.
type UnsafeOPAServiceServer interface {
	mustEmbedUnimplementedOPAServiceServer()
}

func RegisterOPAServiceServer(s grpc.ServiceRegistrar, srv OPAServiceServer) {
	// If the following call pancis, it indicates UnimplementedOPAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OPAService_ServiceDesc, srv)
}

func _OPAService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OPAServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OPAService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OPAServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OPAService_ServiceDesc is the grpc.ServiceDesc for OPAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OPAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gaiaxopa.v1.OPAService",
	HandlerType: (*OPAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _OPAService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opa.proto",
}
